services:
  backend:
    build:
      context: .
    container_name: timesheet-backend-server
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app/backend
      - ./public:/app/public
      - /app/backend/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: timesheet-postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: timesheetdb
    volumes:
      - timesheet_postgres_data_volume:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: timesheet-adminer-ui
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  timesheet_postgres_data_volume:
